---
title: "Classification Attempt2"
author: "Kylie Lin"
date: "5/12/2021"
output: html_document
---

## Attempt \#2

```{r, message = F, warning = F}
library(tidyverse)
library(tidymodels)
library(janitor)
library(skimr)
library(DT)
library(lubridate)
library(naniar)

library(rsample)
library(tidymodels)

```

```{r, message = F, warning = F}
bl_test <- read_csv("stat-301-3-classification-2021-loan-repayment/test.csv") %>% 
  clean_names()

bl_train <- read_csv("stat-301-3-classification-2021-loan-repayment/train.csv") %>% 
  clean_names()

```

```{r}
bl_train <- bl_train %>% 
  mutate(
    hi_int_prncp_pd = ifelse(hi_int_prncp_pd == 0, "0", "1"),
    hi_int_prncp_pd = as.factor(hi_int_prncp_pd)
  )

```

```{r}
bl_folds <- bl_train %>%
  vfold_cv(v = 5, repeats = 1, strata = hi_int_prncp_pd)
bl_folds

```

```{r}
bl_recipe <- recipe(hi_int_prncp_pd ~ out_prncp_inv + int_rate + loan_amnt + term + grade,
                    data = bl_train) %>% 
  step_dummy(term, grade) %>% 
  step_normalize(all_predictors())

```

```{r}
# Model setup and tuning
save(bl_folds, 
     bl_recipe,
     bl_train,
     bl_test,
     file = "model_info/bl_setup.rda")

```